"""autogenerated by genmsg_py from Catcher.msg. Do not edit."""
import roslib.message
import struct


class Catcher(roslib.message.Message):
  _md5sum = "0007f92c016629160356ca5642bbf6b7"
  _type = "tele_doll_catcher/Catcher"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 moveTLR
int16 moveTFB
bool MOVE_RIGHT 
bool MOVE_FORWARD
bool CATCH_OR_NOT

"""
  __slots__ = ['moveTLR','moveTFB','MOVE_RIGHT','MOVE_FORWARD','CATCH_OR_NOT']
  _slot_types = ['int16','int16','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       moveTLR,moveTFB,MOVE_RIGHT,MOVE_FORWARD,CATCH_OR_NOT
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(Catcher, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.moveTLR is None:
        self.moveTLR = 0
      if self.moveTFB is None:
        self.moveTFB = 0
      if self.MOVE_RIGHT is None:
        self.MOVE_RIGHT = False
      if self.MOVE_FORWARD is None:
        self.MOVE_FORWARD = False
      if self.CATCH_OR_NOT is None:
        self.CATCH_OR_NOT = False
    else:
      self.moveTLR = 0
      self.moveTFB = 0
      self.MOVE_RIGHT = False
      self.MOVE_FORWARD = False
      self.CATCH_OR_NOT = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_2h3B.pack(_x.moveTLR, _x.moveTFB, _x.MOVE_RIGHT, _x.MOVE_FORWARD, _x.CATCH_OR_NOT))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.moveTLR, _x.moveTFB, _x.MOVE_RIGHT, _x.MOVE_FORWARD, _x.CATCH_OR_NOT,) = _struct_2h3B.unpack(str[start:end])
      self.MOVE_RIGHT = bool(self.MOVE_RIGHT)
      self.MOVE_FORWARD = bool(self.MOVE_FORWARD)
      self.CATCH_OR_NOT = bool(self.CATCH_OR_NOT)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_2h3B.pack(_x.moveTLR, _x.moveTFB, _x.MOVE_RIGHT, _x.MOVE_FORWARD, _x.CATCH_OR_NOT))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.moveTLR, _x.moveTFB, _x.MOVE_RIGHT, _x.MOVE_FORWARD, _x.CATCH_OR_NOT,) = _struct_2h3B.unpack(str[start:end])
      self.MOVE_RIGHT = bool(self.MOVE_RIGHT)
      self.MOVE_FORWARD = bool(self.MOVE_FORWARD)
      self.CATCH_OR_NOT = bool(self.CATCH_OR_NOT)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2h3B = struct.Struct("<2h3B")
